---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Layout/LineLength:
  Exclude:
    - test/**/*

Minitest/NoAssertions:
  Enabled: false
