---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
